import { mkdir, readFile, rm, stat, writeFile } from 'node:fs/promises'
import { dirname, isAbsolute, join, normalize, resolve, sep } from 'node:path'

export interface StoredFile {
  readonly body: Uint8Array
  readonly size: number
  /** The type the storage serves the file with, when it says (checked after direct uploads). */
  readonly contentType?: string
}

/** Where uploaded files live. Keys are generated by Easy CMS: `<name>-<random>.<ext>`. */
export interface StorageAdapter {
  readonly name: string
  /**
   * The adapter interface it is written for (`ADAPTER_API_VERSION`); Easy CMS refuses another.
   * Leave it out to skip the check.
   */
  readonly apiVersion?: number
  /** Called once with the project root, before any other method. */
  init?(args: { cwd: string }): void | Promise<void>
  put(key: string, data: Uint8Array, options: { contentType: string }): Promise<void>
  get(key: string): Promise<StoredFile | null>
  delete(key: string): Promise<void>
  /**
   * Public URL of a file, or `undefined` to serve it through the REST API
   * (`<api>/media/file/<key>`), as the local adapter does.
   */
  url?(key: string): string | undefined
  /**
   * Lets a browser send a file straight to the storage (large files, past a host's request
   * limit): where to send it and how. The URL must work for `expiresIn` seconds and accept at
   * most `size` bytes. Without it, files are uploaded through the server.
   */
  uploadURL?(
    key: string,
    options: { contentType: string; size: number; expiresIn: number },
  ): Promise<DirectUpload>
  /**
   * The first `bytes` of a file and its whole size, without reading it all (to check a file
   * uploaded straight to the storage); `null` when there is no such file. Default: `get`.
   */
  getStart?(key: string, bytes: number): Promise<StoredFile | null>
}

/** Where and how a browser sends a file straight to the storage (`StorageAdapter.uploadURL`). */
export interface DirectUpload {
  readonly url: string
  readonly method: 'PUT' | 'POST'
  /** Headers to send with the file. */
  readonly headers: Readonly<Record<string, string>>
}

export interface DiskStorageOptions {
  /** Directory, relative to the project root. Default `uploads`. */
  readonly dir?: string
}

/** Stores files on the local disk. Suitable for servers with a persistent filesystem. */
export function diskStorage(options: DiskStorageOptions = {}): StorageAdapter {
  // turbopackIgnore: paths are only known at runtime; without it Next traces the whole project.
  let root = resolve(/* turbopackIgnore: true */ options.dir ?? 'uploads')
  const pathOf = (key: string) => {
    const path = normalize(join(/* turbopackIgnore: true */ root, key))
    if (!path.startsWith(root + sep)) throw new Error(`Invalid storage key "${key}"`)
    return path
  }
  return {
    name: 'local',
    apiVersion: 1,
    init({ cwd }) {
      const dir = options.dir ?? 'uploads'
      root = isAbsolute(dir) ? dir : resolve(/* turbopackIgnore: true */ cwd, dir)
    },
    async put(key, data) {
      const path = pathOf(key)
      await mkdir(dirname(path), { recursive: true })
      await writeFile(path, data, { flag: 'wx' })
    },
    async get(key) {
      const path = pathOf(key)
      const info = await stat(path).catch(() => undefined)
      if (!info?.isFile()) return null
      return { body: new Uint8Array(await readFile(path)), size: info.size }
    },
    async delete(key) {
      await rm(pathOf(key), { force: true })
    },
  }
}
