import {
  Award,
  Bell,
  BookOpen,
  Box,
  Briefcase,
  Building,
  Calendar,
  CalendarDays,
  Camera,
  Car,
  ChartColumn,
  ChartLine,
  CircleHelp,
  File,
  FileText,
  Folder,
  Globe,
  GraduationCap,
  Heart,
  House,
  Image,
  Images,
  KeyRound,
  Layers,
  LayoutGrid,
  Link,
  Mail,
  MapPin,
  Megaphone,
  MessageSquare,
  Music,
  Newspaper,
  Notebook,
  Package,
  Palette,
  Phone,
  Quote,
  Settings,
  ShoppingBag,
  ShoppingCart,
  SlidersHorizontal,
  Star,
  Store,
  Tag,
  Tags,
  Ticket,
  User,
  Users,
  Utensils,
  Video,
} from '@lucide/vue'
import type { Component } from 'vue'

/** The icons `icon` in a collection or global config can name (`ADMIN_ICONS` in core). */
const ICONS: Record<string, Component> = {
  'file-text': FileText,
  newspaper: Newspaper,
  'book-open': BookOpen,
  notebook: Notebook,
  folder: Folder,
  tag: Tag,
  tags: Tags,
  image: Image,
  images: Images,
  video: Video,
  music: Music,
  file: File,
  users: Users,
  user: User,
  building: Building,
  store: Store,
  'shopping-bag': ShoppingBag,
  'shopping-cart': ShoppingCart,
  package: Package,
  box: Box,
  calendar: Calendar,
  'calendar-days': CalendarDays,
  'map-pin': MapPin,
  globe: Globe,
  house: House,
  'layout-grid': LayoutGrid,
  layers: Layers,
  star: Star,
  heart: Heart,
  'message-square': MessageSquare,
  mail: Mail,
  phone: Phone,
  briefcase: Briefcase,
  'graduation-cap': GraduationCap,
  utensils: Utensils,
  car: Car,
  settings: Settings,
  'sliders-horizontal': SlidersHorizontal,
  palette: Palette,
  megaphone: Megaphone,
  bell: Bell,
  link: Link,
  quote: Quote,
  'circle-help': CircleHelp,
  award: Award,
  ticket: Ticket,
  camera: Camera,
  key: KeyRound,
  'chart-column': ChartColumn,
  'chart-line': ChartLine,
}

export const collectionIcon = (name?: string): Component => (name && ICONS[name]) || FileText
export const globalIcon = (name?: string): Component => (name && ICONS[name]) || Settings

/** Every name, for the test that keeps this list in step with core's `ADMIN_ICONS`. */
export const ICON_NAMES = Object.keys(ICONS)
